var fs = require('fs');
var c = fs.readFileSync('src/app/page.tsx', 'utf8');
var start = c.indexOf('function printReceipt(');
var end = c.indexOf('function localDateStr');
var before = c.substring(0, start);
var after = c.substring(end);
var oldFn = c.substring(start, end);
console.log('Old function length:', oldFn.length);
console.log('Has nested backticks:', oldFn.includes('html = `'));
fs.writeFileSync('_old_fn.txt', oldFn);
console.log('Saved old function to _old_fn.txt');
